# 1.K近邻代码的实现

In [1]:
import numpy as np
from math import sqrt
from collections import Counter

def KNN_classify(k,x_train,y_train,x):
    assert 1<=k<=x_train.shape[0]           # 断言
    assert x_train.shape[0]==y_train.shape[0]
    assert x_train.shape[1]==x.shape[0]
    
    distances=[sqrt(np.sum((x_t-x)**2)) for x_t in x_train]
    nearest=np.argsort(distances)
    
    topk_y=[y_train[i]  for  i  in  nearest[:k]]
    votes=Counter(topk_y)
    
    return votes.most_common(1)[0][0]  

In [2]:
import matplotlib.pyplot as plt

raw_data_x=[[7.00437122, 8.44186643],
       [6.76514336, 7.27858057],
       [9.51457957, 0.12703197],
       [4.13587699, 0.48812794],
       [5.99928561, 5.08066306],
       [2.00247539, 7.44154169],
       [1.92892003, 7.00844752],
       [2.93228106, 7.74479454],
       [0.05108839, 1.12857654],
       [1.10953672, 2.47668229]]
raw_data_y=[0,0,0,0,0,1,1,1,1,1]

x_train=np.array(raw_data_x)
y_train=np.array(raw_data_y)
x_temp=np.array([0.093607318,3.365731514])

In [3]:
p_y=KNN_classify(6,x_train,y_train,x_temp)

In [4]:
p_y

1

# 2.使用scikit-learn中的KNN

In [5]:
from sklearn.neighbors import KNeighborsClassifier
KNN_classifier=KNeighborsClassifier(n_neighbors=6)
KNN_classifier.fit(x_train,y_train)##拟合我们的训练集

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [6]:
KNN_classifier.predict([x_temp])

array([1])

In [7]:
x_predict=x_temp.reshape(1,-1)

In [8]:
x_predict

array([[0.09360732, 3.36573151]])

In [9]:
KNN_classifier.predict(x_predict)

array([1])

In [10]:
y_predict=KNN_classifier.predict(x_predict)

In [11]:
y_predict[0]

1

# 3.重新整理KNN算法

In [14]:
import sys
sys.path.append("F:/PYCharm/PYCode")####假如模块搜索的路径
from machine_learning.KNN_classifier import KNN_classifier

In [15]:
KNN_result=KNN_classifier(k=6)

In [16]:
KNN_result.fit(x_train,y_train)

In [17]:
y_predict=KNN_result.predict(x_predict)

In [18]:
y_predict

array([1])

# 4.测试我们的算法

In [19]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn import datasets

In [20]:
iris=datasets.load_iris()

In [21]:
x=iris.data

In [22]:
y=iris.target

In [23]:
print(x.shape)
print(y.shape)
print(x)
print("______________________________________________________________________")
print(y)

(150, 4)
(150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

## train_test_split 训练 测试 数据集的拆分

### np.random.permutation(n):0--(n-1)的随机排列

In [24]:
shuffle_index=np.random.permutation(len(x))##乱序排列
shuffle_index

array([ 53, 127,   8,  16, 101, 140,   5,  93,  71,  66,  62, 110, 108,
       135, 141,  15, 116,  49,   9,  74,  18,  38,  78, 121,  20,  59,
        24,  86, 122, 126,  54,  72,  94,  31,  10,  17,  68,  96,  33,
       120,  98,  57,   6,  60,  58, 105,  87,  42, 114,  73,  91,  69,
       132, 111,   2,  14,  26, 125,  25,  41, 143, 138,  77,  83, 109,
       146, 144,  28, 134, 137,  97,  45,  89,   1, 139,  63,  84,  81,
        92, 129,  90,  95,  47,  70,  36,  61,  11, 131, 115,  19, 145,
       147, 149,  67,  48, 124,  55,  99,  32, 107, 102, 104,   0,  39,
         7,   4,  46,  34, 118,  79,  21,  27,  13,  82, 133,  85,  52,
       136, 128,  30,  50, 113, 100, 112,  80, 103,  40,  43, 130,  75,
        22, 148,  51, 119, 142,  44,  76, 117, 123,  65,  29,  35,   3,
        12, 106,  88,  23,  37,  64,  56])

In [25]:
test_ratic=0.2
test_size=int(len(x)*test_ratic)
test_size

30

In [26]:
test_index=shuffle_index[:test_size]

In [27]:
train_index=shuffle_index[test_size:]

In [28]:
x_train=x[train_index]
y_train=y[train_index]

x_test=x[test_index]
y_test=y[test_index]

In [29]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


### 使用封装的算法 

In [30]:
import sys
sys.path.append("F:/PYCharm/PYCode")####假如模块搜索的路径
from machine_learning.model_selection import train_test_split

In [31]:
x_train,y_train,x_test,y_test=train_test_split(x,y)

In [32]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [33]:
from machine_learning.KNN_classifier import KNN_classifier

In [34]:
my_knn=KNN_classifier(k=3)
my_knn.fit(x_train,y_train)

In [35]:
y_predict=my_knn.predict(x_test)

In [36]:
y_predict

array([0, 0, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 0, 2, 1, 0, 0, 2, 2, 2, 2, 1,
       2, 0, 0, 0, 1, 0, 0, 1])

In [37]:
y_test

array([0, 0, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 0, 2, 1, 0, 0, 2, 2, 2, 2, 1,
       2, 0, 0, 0, 1, 0, 0, 1])

In [38]:
sum(y_predict==y_test)

30

In [39]:
sum(y_predict==y_test)/len(y_test)

1.0