# 庞大的函数库——大小排序

1.min(),max():分别计算数组的最大值、最小值#####  ptp():计算最大值最小值之间的差#####  maximum():比较两个数组对应的下标的元素,返回数组的形状是量参数组广播之后的形状。

2.argmax/argmin(a, axis=None, out=None)：可以求最大值最小值的下标,使用axis时可以沿着指定轴计算最大值的下标。 ravel(a, order='C'):返回一个连续的扁平数组

3.unravel_index(indices, dims, order='C'):将一维数组的下标转换为多维数组的下标，第一个参数为一维数组的下标，第二个参数为多维数组的形状

4.sort(a, axis=-1, kind='quicksort', order=None)：sort()函数对数组进行排序,会返回一个新数组，不改变原始数组（数组的sort（）会改变,例如列表使用sort（）排序）；
axis默认值为-1(沿数组最终轴进行排序)，axis值为none（得到平坦化之后进行排序的新数组）,axis值为0（对每一列上进行排序）

5.argsort(a, axis=-1, kind='quicksort', order=None)：范回数组的排序下标，axis默认为-1

6.arange函数产生的是一维数组，而ogrid函数产生的是二维数组、、arange函数产生的是一个数组，而ogrid函数产生的是二个数组、、ogrid函数产生的数组，第一个数组是以纵向产生的，即数组第二维的大小始终为1。第二个数组是以横向产生的，即数组第一维的大小始终为1。   默认步长为1

7.lexsort(keys, axis=-1):参数是一个形状为（k，N）,可以理解为Excel中N行k列的表格（传入K个长度为n的数组的序列）。返回排序下标,数组中最后的列为排列的主键。

8.partition(a, kth, axis=-1, kind='introselect', order=None):对数组进行分割，可以很快找出排序之后的前k个元素，详见下面的例子。。以极大的运行速度优于sort().

9.median(a, axis=None, out=None, overwrite_input=False, keepdims=False):获得数组的中间值，当长度为偶数时，则取中间两个数的平均值。

10.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)：用于计算八分位数，即将数值从小到大排列，计算处于p%位置上的值。

In [1]:
import numpy as np

In [2]:
a=np.array([1,3,5,7,9])

In [3]:
b=np.array([2,4,6,8])

In [4]:
print(a[None,:])#############    None表示切片
print(b[:,None])
np.maximum(a[None,:],b[:,None])

[[1 3 5 7 9]]
[[2]
 [4]
 [6]
 [8]]


array([[2, 3, 5, 7, 9],
       [4, 4, 5, 7, 9],
       [6, 6, 6, 7, 9],
       [8, 8, 8, 8, 9]])

In [5]:
np.random.seed(42)
a=np.random.randint(0,10,size=(4,5))
print(a)
ma=np.argmax(a)
a=np.random.randint(0,10,size=(4,5))
print(a)
ma=np.argmax(a)
ma

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]]
[[4 0 9 5 8]
 [0 9 2 6 3]
 [8 2 4 2 6]
 [4 8 6 1 3]]


2

In [6]:
print(np.ravel(a,order='K'))


[4 0 9 5 8 0 9 2 6 3 8 2 4 2 6 4 8 6 1 3]


In [7]:
mas=np.argmax(a,axis=1)
mas

array([2, 1, 0, 1], dtype=int64)

In [8]:
print(a.shape[0])###########0表示按行
a[np.arange(a.shape[0]),mas]###########可选出每个最大值

4


array([9, 9, 8, 8])

In [9]:
a


array([[4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3]])

In [10]:
np.sort(a)

array([[0, 4, 5, 8, 9],
       [0, 2, 3, 6, 9],
       [2, 2, 4, 6, 8],
       [1, 3, 4, 6, 8]])

In [11]:
np.sort(a,axis=0)##########对每一列进行排序

array([[0, 0, 2, 1, 3],
       [4, 2, 4, 2, 3],
       [4, 8, 6, 5, 6],
       [8, 9, 9, 6, 8]])

In [12]:
sort1=np.argsort(a)
sort2=np.argsort(a,axis=0)

In [13]:
print(sort1)
print(sort2)

[[1 0 3 4 2]
 [0 2 4 3 1]
 [1 3 2 4 0]
 [3 4 0 2 1]]
[[1 0 1 3 1]
 [0 2 2 2 3]
 [3 3 3 0 2]
 [2 1 0 1 0]]


In [14]:
axis0,axis1=np.ogrid[:a.shape[0],:a.shape[1]]########### 产生第0轴和第一轴的下标

In [15]:
a[axis0,sort1]####  axis0第0个轴（对横轴进行操作）的坐标，sort1表示///////对行进行排序

array([[0, 4, 5, 8, 9],
       [0, 2, 3, 6, 9],
       [2, 2, 4, 6, 8],
       [1, 3, 4, 6, 8]])

In [16]:
a[sort2,axis1]####  
print("#########################################")
print(axis0)
print("#########################################")
print(axis1)

#########################################
[[0]
 [1]
 [2]
 [3]]
#########################################
[[0 1 2 3 4]]


In [17]:
a[sort2,axis1]####对列进行排序

array([[0, 0, 2, 1, 3],
       [4, 2, 4, 2, 3],
       [4, 8, 6, 5, 6],
       [8, 9, 9, 6, 8]])

In [18]:
a[axis0,sort1]

array([[0, 4, 5, 8, 9],
       [0, 2, 3, 6, 9],
       [2, 2, 4, 6, 8],
       [1, 3, 4, 6, 8]])

In [19]:
names=["zhang","wang","li","wang","zhang"]
ages=[37,33,32,31,36]
idx=np.lexsort([ages,names])
print(idx)
a_temp=np.array(list(zip(names,ages)),"O")[idx]
######  给array() 传入序列对象来创建数组，多层嵌套则创建多维数组

[2 3 1 4 0]


In [20]:
a_temp

array([['li', 32],
       ['wang', 31],
       ['wang', 33],
       ['zhang', 36],
       ['zhang', 37]], dtype=object)

In [21]:
b=np.random.randint(0,10,(5,3))
a=np.random.randint(0,10)
print(a)
print(b)

3
[[8 1 9]
 [8 9 4]
 [1 3 6]
 [7 2 0]
 [3 1 7]]


In [22]:
b[:,::-1].T##### ::-1 倒序  .T转置

array([[9, 4, 6, 0, 7],
       [1, 9, 3, 2, 1],
       [8, 8, 1, 7, 3]])

In [23]:
np.lexsort(b[:,::-1].T)

array([2, 4, 3, 0, 1], dtype=int64)

In [24]:
b[np.lexsort(b[:,::-1].T)]

array([[1, 3, 6],
       [3, 1, 7],
       [7, 2, 0],
       [8, 1, 9],
       [8, 9, 4]])

In [25]:
r=np.random.randint(0,1000000,100000)
r

array([805889, 459773, 208261, ...,  60820, 430571, 794306])

In [26]:
np.sort(r)[:5]

array([ 5, 13, 15, 27, 37])

In [27]:
print(b.sort())

None


In [28]:
np.partition(r,2)

array([     5,     13,     15, ...,  60820, 430571, 794306])

In [31]:
a=np.random.randint(0,10,size=(4,5))
print(a)

[[8 7 2 9 4]
 [4 4 7 2 2]
 [7 8 4 9 7]
 [4 3 1 3 1]]


In [32]:
a

array([[8, 7, 2, 9, 4],
       [4, 4, 7, 2, 2],
       [7, 8, 4, 9, 7],
       [4, 3, 1, 3, 1]])

In [33]:
np.median(a,axis=1)

array([7., 4., 7., 3.])

In [36]:
r=np.abs(np.random.randn(100000))

In [37]:
r

array([0.16811019, 0.02952086, 1.01371257, ..., 0.34946832, 0.64147451,
       0.12875561])

In [38]:
np.percentile(r,[68.3,95.4,99.7]) 
###计算标准正态分布的绝对值在68.3%、。。。的百分位数，他们应该约等于标准差的一倍二倍三倍。

array([1.00057639, 2.00364613, 2.95337579])

In [39]:
a=[2,4,8,16,16,32]
v=[1,5,33,16]

In [40]:
np.searchsorted(a,v)

array([0, 2, 6, 3], dtype=int64)

In [42]:
np.searchsorted(a,v,side="right")

array([0, 2, 6, 5], dtype=int64)