# Numpy学习笔记

In [3]:
import numpy
#将比较矩阵里面每一个元素和给定的值是否相等，是：返回true 否：返回flase
vector=numpy.array([2,6,4,6])
vector==6

array([False,  True, False,  True])

numpy.genfromtext("hh.txt",delimit=",",dtype=str)   
genfromtext函数可以实现打开TXT文档

array: 当传入一个list格式，会自动转化。
       传入的值统一，不同会自动转化
dtype:显示numpy中的类型
shape:显示几行几列

In [4]:
vector

array([2, 6, 4, 6])

In [5]:
matrix=numpy.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])
matrix==25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [6]:
vector=numpy.array([5,10,15,20])
equal_to_ten_to_five=(vector==5)&(vector==10)  #与   vector等于5且vector等于10
print(equal_to_ten_to_five)

[False False False False]


In [7]:
matrix[:,1]   ##第二列

array([10, 25, 40])

In [8]:
matrix[1,:] ##第二行

array([20, 25, 30])

In [9]:
######numpy中的类型转化问题
vector=numpy.array(["1","2","3"])
print(vector.dtype)              #dtype
print(vector)
vector=vector.astype(float)     #astype可以转化矩阵中所有元素的类型
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [10]:
matrix.min()

5

In [11]:
matrix.sum(axis=1)  ##指定1，按列求和
matrix.sum(axis=1)  ##指定0，按行求和

array([ 30,  75, 120])

In [12]:
import numpy as np
print(np.arange(15))
a=np.arange(15).reshape(3,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

np.arange(15):可以直接生成0-14的一维向量
reshape（3,5）：将一维向量变成3行5列
shape：可看出向量是几行几列
size：显示多少个元素

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.arange(10,30,5)

array([10, 15, 20, 25])

zeros((x,y)):传入元组，生成几行几列的0矩阵，默认float
ones(（x,y），dtype=np.int32):传入元组，用dtype转化成numpy支持的格式。1矩阵。
arange(x,y,z):大于等于x,小于y,步长为5的向量
random（2，3）：传入元组，2行3列

In [16]:
np.random.random((2,3))

array([[0.55551637, 0.17417439, 0.28204658],
       [0.45206906, 0.32692428, 0.55338843]])

In [17]:
from  numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

linspace(x,y,z):x-起始值，y-终点值，z个数。
dot:表示矩阵的乘

In [18]:
A=np.array([[1,1],
           [0,1]])
B=np.array([[1,1],
          [0,1]])
print(A)
print("--------")
print(B)
print("--------")
print(A*B)
print("--------")
print(A.dot(B))
print("--------")
print(np.dot(A,B))

[[1 1]
 [0 1]]
--------
[[1 1]
 [0 1]]
--------
[[1 1]
 [0 1]]
--------
[[1 2]
 [0 1]]
--------
[[1 2]
 [0 1]]


In [19]:
import numpy as np
B=np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [20]:
a=np.floor(10*np.random.random((3,4)))
print(a)
print("------------------------------------------")
print(a.ravel())
print("------------------------------------------")
a.shape=(6,2)
print(a)
print("------------------------------------------")
print(a.T)

[[1. 5. 0. 8.]
 [6. 1. 4. 0.]
 [9. 2. 0. 5.]]
------------------------------------------
[1. 5. 0. 8. 6. 1. 4. 0. 9. 2. 0. 5.]
------------------------------------------
[[1. 5.]
 [0. 8.]
 [6. 1.]
 [4. 0.]
 [9. 2.]
 [0. 5.]]
------------------------------------------
[[1. 0. 6. 4. 9. 0.]
 [5. 8. 1. 0. 2. 5.]]


In [21]:
a=np.floor(10*np.random.random((3,2)))
b=np.floor(10*np.random.random((3,2)))
print(np.vstack((a,b)))

[[6. 0.]
 [0. 3.]
 [7. 1.]
 [8. 5.]
 [9. 1.]
 [3. 8.]]


np.floor():取整

a.ravel():将矩阵变为向量，拉长

a.shape=(6,2)：切分矩阵为几行几列

a.T：矩阵转置

np.vstack((a,b):按行拼接两个矩阵

np.hstack((a,b)：按列拼接两个矩阵

In [22]:
a=np.floor(10*np.random.random((2,12)))
print(np.hsplit(a,3))
print(np.hsplit(a,(3,4)))

[array([[8., 1., 1., 7.],
       [7., 4., 8., 1.]]), array([[8., 6., 6., 7.],
       [7., 7., 8., 1.]]), array([[6., 9., 0., 2.],
       [0., 0., 5., 3.]])]
[array([[8., 1., 1.],
       [7., 4., 8.]]), array([[7.],
       [1.]]), array([[8., 6., 6., 7., 6., 9., 0., 2.],
       [7., 7., 8., 1., 0., 0., 5., 3.]])]


np.hsplit(a,3):按列将a矩阵平均分成三份

np.hsplit(a,(3,4))：按列将a从第三列切一刀，在从第四列切一刀，平均分成三份   

np.vsplit(a,3):按行

np.vsplit(a,(3,4))：按行 

In [23]:
a=np.arange(12)
b=a
print(b is a)
b.shape=3,4
print(a.shape)
print(a)
print(id(a))
print(id(b))

True
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
129102512
129102512


In [24]:
c=a.view()   ####浅复制，c变，a会跟着变,,和等号一样
print(c is a )
c.shape=2,6
print(a.shape)
c[0,4]=1234
print(a)
print(id(a))
print(id(c))

False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
129102512
129102672


In [25]:
d=a.copy()   ####复制，c变，a不变
print(d is a )

d[0,0]=9999
print(a)
print(d)
print(id(a))
print(id(c))

False
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
129102512
129102672


x.argmax(axis=0):按列进行选择最大值

a.copy()   ####复制，c变，a不变

c=a.view()   ####浅复制，c变，a会跟着变,,和等号一样

np.tile(a,(4,2))#######复制，如下

In [26]:
a=np.arange(0,40,10)
print(a)
b=np.tile(a,(4,2))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [29]:
a=np.arange(0,60,10).reshape(-1,1)+np.arange(0,6)

In [30]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [32]:
a[(0,1,2,3),(1,2,3,4)] ####对应的是第0轴第一轴，相当啊a[0,1],a[1,2],a[2,3],a[3,4]

array([ 1, 12, 23, 34])