## 1.随机数

1.rand()：产生0-1之间的随机浮点数,括号内用于产生数组的形状；  randn():产生标准正态的随机数，括号内用于产生数组的形状；  randint():产生指定范围的随机整数，包含起始值，但不包含终值，第三个参数表示形状

2.最后一个参数表示输出数组的形状：normal（）：正态分布，前两个参数表示期望值和标准差； uniform（）：均匀分布，前两个参数分别为区间的起始终值
poisson:泊松分布，第一个参数是入参数，单位时间内随机时间的平均发生率。————输出整数数组

3.permutation():用于产生一个乱序数组，参数为n,则返回[0,n)整数的随机排列。参数为一个序列时，返回随机排列的序列。

4.np.random.shuffle():将参数数组的顺序打乱

5.np.random.choice():

6.seed():

In [1]:
import numpy as np

In [2]:
r1=np.random.rand(4,3)
r2=np.random.randn(4,3)
r3=np.random.randint(0,10,(4,3))
print(r1)
print("000000000000000000000000000000000000000000")
print(r2)
print("000000000000000000000000000000000000000000")
print(r3)

[[0.20091487 0.9821852  0.58154803]
 [0.43648823 0.21425705 0.88097408]
 [0.46117973 0.73353106 0.6202163 ]
 [0.18905231 0.54920863 0.81103729]]
000000000000000000000000000000000000000000
[[-0.40268091 -0.47825516  0.91564005]
 [-0.31972784  1.58776847 -1.14891749]
 [-2.24412517  1.22968642  0.68866883]
 [-0.68141738 -2.13796919 -0.81917391]]
000000000000000000000000000000000000000000
[[6 9 5]
 [3 3 9]
 [0 8 4]
 [1 3 1]]


In [3]:
rr1=np.random.normal(100,10,(4,3))
rr2=np.random.uniform(10,20,(4,3))
rr3=np.random.poisson(2.0,(4,3))
print(rr1)
print("000000000000000000000000000000000000000000")
print(rr2)
print("000000000000000000000000000000000000000000")
print(rr3)

[[ 93.64468782 107.88797804 103.45778357]
 [ 87.58092355  87.67547402 106.58309127]
 [ 99.11088476 132.46179946  93.95511238]
 [ 88.91230479 117.37056327  91.46432387]]
000000000000000000000000000000000000000000
[[17.25874729 12.09592363 17.35958433]
 [18.79945852 17.07667501 13.75995194]
 [12.638072   16.16356599 17.77201696]
 [16.53219663 13.53669084 11.65535994]]
000000000000000000000000000000000000000000
[[3 1 3]
 [1 0 4]
 [1 2 3]
 [2 2 2]]


In [4]:
a=np.array([1,10,20,30,40])
print(a)

[ 1 10 20 30 40]


In [5]:
print(np.random.permutation(10))
print(np.random.permutation(a))

[4 7 0 8 6 1 5 9 3 2]
[10 20 40  1 30]


In [6]:
a=np.arange(10,25,dtype=float)
c1=np.random.choice(a,size=(4,3),replace=False)
c2=np.random.choice(a,size=(4,3),p=a/np.sum(a))
c3=np.random.choice(a,size=(4,3))
print(a)
print("_______________________________")
print(c1)
print("_______________________________")
print(c2)
print("_______________________________")
print(c3)


[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.]
_______________________________
[[17. 12. 23.]
 [14. 24. 21.]
 [10. 19. 16.]
 [13. 15. 22.]]
_______________________________
[[23. 13. 19.]
 [14. 14. 19.]
 [22. 15. 24.]
 [15. 22. 24.]]
_______________________________
[[19. 10. 15.]
 [21. 14. 18.]
 [18. 14. 18.]
 [21. 18. 14.]]


# 2.求和，平均数，方差

1.np.sum():计算所有元素的和，axis = 0(（第0轴）第一维度相加)表示对最外层[]里的最大单位块做块与块之间的运算,同时移除最外层[];;;;axis=1表示第二外层[];;;;axis=n表示第n外层[];;;axis=(x,y)则求第X,第Y的轴的和；；；；；；；；；；；；；；；；；sum(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)keepdims为TRUE时，可以保持原数组的维数；；当出现溢出问题以及想改变累加变量类型，用dtype指定。；；；；；；也可用out数组，但形状必须和结果数组的形状相同

2.np.double:双精度

3.mean(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)::求平均值

4.average(a, axis=None, weights=None, returned=False):求平均值，weights属性可以计算加权平均数  

5.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<class 'numpy._globals._NoValue'>)：计算标准差；；ddof=0时计算偏样本方差，ddof=1计算无偏样本方差

6.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<class 'numpy._globals._NoValue'>)：计算方差

In [24]:
np.random.seed(42)
a=np.random.randint(0,10,size=(4,5))
print(a)
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
print(np.sum(a,axis=1)/5)
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
print(np.ones((2,3,4)))

print(np.sum(np.ones((2,3,4)),axis=(0,2)))#######表示3行4列，两个数组

#########axis=(0,2)

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[5.2 5.6 4.8 3.6]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[8. 8. 8.]


In [21]:
np.mean(a,axis=1)

array([5.2, 5.6, 4.8, 3.6])

In [26]:
s=np.array([83,72,79])
n=np.array([20,15,30])
print(np.average(s,weights=n))  ####相当于  np.sum(c*n)/np.sum(n,dtype=float)

78.61538461538461
