# 如何调试梯度

In [3]:
import numpy as np 
import matplotlib.pyplot as plt

In [5]:
np.random.seed(666)
x=np.random.random(size=(1000,10))

In [6]:
true_theta=np.arange(1,12,dtype=float)

In [8]:
x_b=np.hstack([np.ones((len(x),1)),x])#####按列叠加起来
y=x_b.dot(true_theta)+np.random.normal(size=1000)

In [9]:
x.shape

(1000, 10)

In [10]:
y.shape

(1000,)

In [11]:
true_theta

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [12]:
x_b

array([[1.        , 0.70043712, 0.84418664, ..., 0.04881279, 0.09992856,
        0.50806631],
       [1.        , 0.20024754, 0.74415417, ..., 0.11285765, 0.11095367,
        0.24766823],
       [1.        , 0.0232363 , 0.72732115, ..., 0.25913185, 0.58381262,
        0.32569065],
       ...,
       [1.        , 0.88593917, 0.49480495, ..., 0.50598273, 0.86447115,
        0.31128276],
       [1.        , 0.81051618, 0.87890841, ..., 0.37299025, 0.81523744,
        0.31074351],
       [1.        , 0.75052272, 0.98612317, ..., 0.26679141, 0.34224855,
        0.02366081]])

In [13]:
def J(theta,x_b,y):
    try:
        return  np.sum(((y-x_b.dot(theta))**2))/len(x_b)                         
#np.dot(A, B)：对于二维矩阵，计算真正意义上的矩阵乘积，同线性代数中矩阵乘法的定义。对于一维矩阵，计算两者的内积
    except:
        return float('inf')

def dJ_math(theta,x_b,y):
    return x_b.T.dot(x_b.dot(theta)-y)*2./len(y)

In [16]:
def dJ_debug(theta,x_b,y,epsilon=0.01):          ###########很重要
    res=np.empty(len(theta))
    for i in range(len(theta)):
        theta_1=theta.copy()
        theta_1[i]+=epsilon
        theta_2=theta.copy()
        theta_2[i]-=epsilon
        res[i]=(J(theta_1,x_b,y)-J(theta_2,x_b,y))/(2*epsilon)
    return  res

In [17]:
def gradient_descent(dJ,x_b ,y , initial_theta , eta, n_iters=1e4):
    theta=initial_theta 
    i_iter=0
    esplion=1e-8
    
    while i_iter<n_iters:
        gradient=dJ(theta,x_b,y)
        last_theta=theta
        theta=theta-eta * gradient  ###迭代 让theta每次都能向导数的负方向移一步

        if(abs((J(last_theta,x_b,y)-J(theta,x_b,y)).any())<esplion):
              break
        i_iter+=1
    return theta

In [18]:
x_b=np.hstack([np.ones((len(x),1)),x])
initial_theta=np.zeros(x_b.shape[1])
eta=0.01

%time theta=gradient_descent(dJ_debug,x_b, y, initial_theta, eta)
theta

Wall time: 3.61 s


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

In [19]:
%time theta=gradient_descent(dJ_math,x_b, y, initial_theta, eta)
theta

Wall time: 663 ms


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])