# 梯度下降算法

In [25]:
import numpy as np
import matplotlib.pyplot as plt


In [26]:
m=100000
x=np.random.normal(size=m)
X=x.reshape(-1,1)
y=x*4.+3.+np.random.normal(0,3,size=m)

In [27]:
def J(theta,x_b,y):
    try:
        return  ((y-x_b.dot(theta))**2)/len(x_b)                         
#np.dot(A, B)：对于二维矩阵，计算真正意义上的矩阵乘积，同线性代数中矩阵乘法的定义。对于一维矩阵，计算两者的内积
    except:
        return float('inf')
    
def dJ(theta,x_b,y):      #dot函数矩阵乘
    res=np.empty(len(theta))  
    #empty一样,它所常见的数组内所有元素均为空
    res[0]=np.sum(x_b.dot(theta)-y)
    for i in range(1,len(theta)):
        res[i]=(x_b.dot(theta)-y).dot(x_b[:,1])
    return res*2/len(x_b)

def gradient_descent(x_b ,y , initial_theta , eta, n_iters=1e4):
    theta=initial_theta 
    i_iter=0
    esplion=1e-8
    
    while i_iter<n_iters:
        gradient=dJ(theta,x_b,y)
        last_theta=theta
        theta=theta-eta * gradient  ###迭代 让theta每次都能向导数的负方向移一步

        if(abs((J(last_theta,x_b,y)-J(theta,x_b,y)).any())<esplion):
              break
        i_iter+=1
    return theta

In [28]:
%%time
x_b=np.hstack([np.ones((len(x),1)),x.reshape(-1,1)])
initial_theta=np.zeros(x_b.shape[1])
eta=0.01

theta=gradient_descent(x_b, y, initial_theta, eta)

Wall time: 4.84 s


In [29]:
theta

array([2.99936539, 3.99912745])

# 随机下降算法

In [46]:
def dJ_sgd(theta,x_b_i,y_i):      #dot函数矩阵乘

    return x_b_i.T.dot(x_b_i.dot(theta)-y_i)*2.

In [47]:
def sgd(x_b,y,initial_theta,n_iters):
    t0=5
    t1=50
    
    def learning_rate(t):
        return t0/(t+t1)
    theta=initial_theta
    for cur_iter in range(n_iters):
        rand_i=np.random.randint(int(len(x_b)))
        gradient=dJ_sgd(theta,x_b[rand_i],y[rand_i])
        theta=theta-learning_rate(cur_iter)*gradient
    return theta 
    

In [49]:
%%time

x_b=np.hstack([np.ones((len(x),1)),x.reshape(-1,1)])
initial_theta=np.zeros(x_b.shape[1])
theta=sgd(x_b, y, initial_theta, n_iters=len(x_b)//3)########只检测了三分之一个样本，

Wall time: 239 ms


In [50]:
theta

array([2.9413184, 3.9992514])

# 使用自己的随机梯度下降方法

In [35]:
import numpy as np 
import matplotlib.pyplot as plt
import sys
sys.path.append("F:/PYCode")####假如模块搜索的路径
from machine_learning.LinearRegression import LinearRegression

In [36]:
m=100000
x=np.random.normal(size=m)
X=x.reshape(-1,1)
y=x*4.+3.+np.random.normal(0,3,size=m)

In [37]:
lin_r = LinearRegression()

In [38]:
lin_r.fit_sgd(X, y, n_iters = 2)

LinearRegression()

In [39]:
lin_r.coef_

array([3.98140876])

In [41]:
lin_r.interception_

3.0032166326681162

# 真实数据的使用

In [42]:
from machine_learning.model_selection import train_test_split
from  sklearn import datasets

boston = datasets.load_boston()
x= boston.data
y = boston.target

x1 = x[y<50.0]
y1 = y[y<50.0]

x_train,y_train,x_test,y_test=train_test_split(x1,y1,seed =666)

In [51]:
from sklearn.preprocessing import StandardScaler

stand =  StandardScaler()
stand.fit(x_train)
x_train_stand = stand.transform(x_train)
x_test_stand = stand.transform(x_test)

In [52]:
from machine_learning.LinearRegression import LinearRegression
lin_reg10 = LinearRegression()
%time lin_reg10.fit_sgd(x_train_stand,y_train,n_iters=2)
lin_reg10.score(x_test_stand,y_test)

Wall time: 11 ms


0.5680159406026453

In [53]:
from machine_learning.LinearRegression import LinearRegression
lin_reg10 = LinearRegression()
%time lin_reg10.fit_sgd(x_train_stand,y_train,n_iters=50)
lin_reg10.score(x_test_stand,y_test)

Wall time: 122 ms


0.813447000504467

In [54]:
from machine_learning.LinearRegression import LinearRegression
lin_reg10 = LinearRegression()
%time lin_reg10.fit_sgd(x_train_stand,y_train,n_iters=100)
lin_reg10.score(x_test_stand,y_test)

Wall time: 196 ms


0.813017194987496

#  scikit-learn中的使用

In [55]:
from sklearn.linear_model import SGDRegressor

In [56]:
sgd_reg = SGDRegressor()

In [58]:
from machine_learning.model_selection import train_test_split
from  sklearn import datasets

boston = datasets.load_boston()
x= boston.data
y = boston.target

x1 = x[y<50.0]
y1 = y[y<50.0]

x_train,y_train,x_test,y_test=train_test_split(x1,y1,seed =666)

from sklearn.preprocessing import StandardScaler

stand =  StandardScaler()
stand.fit(x_train)
x_train_stand = stand.transform(x_train)
x_test_stand = stand.transform(x_test)

In [59]:
%time sgd_reg.fit(x_train_stand,y_train)
sgd_reg.score(x_test_stand,y_test)

Wall time: 1e+03 µs


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


0.8032705751514354