# F1 score

In [1]:
import numpy as np 


In [7]:
def f1_score(precision, recall): ### 精准率和召回率的调和平均数
    try:
        return (2 * precision * recall) / (precision + recall)
    except:
        return 0.0
    

In [8]:
precision = 0.5
recall = 0.5
f1_score(precision, recall)

0.5

In [9]:
precision = 0.1
recall = 0.9
f1_score(precision, recall)

0.18000000000000002

In [10]:
precision = 0.0
recall = 1.0
f1_score(precision, recall)

0.0

In [11]:
from sklearn import datasets 
digits = datasets.load_digits()
x = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

# scikit-learn中的f1 score

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=666)

from sklearn.linear_model import   LogisticRegression
 
log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)#############penalty='l2  :默认使用L2
log_reg.score(x_test, y_test)

0.9755555555555555

In [13]:
y_log_predict = log_reg.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
confusion_matrix(y_test,y_log_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [16]:
from sklearn.metrics import precision_score
precision_score(y_test, y_log_predict)

0.9473684210526315

In [21]:
from sklearn.metrics import recall_score
recall_score(y_test, y_log_predict)

0.8

In [23]:
from sklearn.metrics import f1_score
f1_score(y_test, y_log_predict)      ##比0.975 更好的衡量我们这个算法

0.8674698795180723

In [28]:
decision_score = log_reg.decision_function(x_test) ##得出的是score值

In [26]:
log_reg.decision_function(x_test)[:10]

array([-22.05699791, -33.02942562, -16.2133534 , -80.37914851,
       -48.25123328, -24.54005871, -44.39165217, -25.04294668,
        -0.97828045, -19.71743647])

In [27]:
log_reg.predict(x_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.max(decision_score)

19.889609256987644

In [30]:
np.min(decision_score)

-85.68610955660012

In [38]:
y_predict_2 = np.array(decision_score >= 5, dtype = 'int') 
### 调动阈值

In [39]:
precision_score(y_test, y_predict_2)

0.96

In [40]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [43]:
y_predict_3 = np.array(decision_score >= -5, dtype = 'int') 
### 调动阈值

In [44]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [45]:
recall_score(y_test, y_predict_3)

0.8888888888888888