# 个人逻辑回归编程的实现

In [25]:
from sklearn import datasets
import numpy as np 
import sys
sys.path.append("F:/PYCode")####假如模块搜索的路径

In [26]:
iris=datasets.load_iris()###纸鸢花数据集
x=iris.data
y=iris.target
x=x[y<2,:2] #####只剩下两种分类0,1，只取前两个特征
y=y[y<2]

### 将数据集切分为2:8 

In [27]:
def train_test_split(x ,y , test_ratic, seed):
    assert  0.0 <= test_ratic <= 1.0
    assert  x.shape[0] == y.shape[0]
    
    
    if(seed):
        np.random.seed(seed)
    
    shuffe_index = np.random.permutation(len(x))
    test_size = int(len(shuffe_index)*test_ratic)
    train_index = shuffe_index[test_size:]
    test_index = shuffe_index[:test_size]
    x_train = x[train_index]
    x_test = x[test_index]
    y_train = y[train_index]
    y_test = y[test_index]
    
    return x_train, x_test, y_test, y_train
    

In [28]:
x_train, x_test, y_test, y_train = train_test_split(x ,y , test_ratic = 0.2, seed=666)
print(y_train)
print(y_test)

[0 0 1 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 1
 0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 0 1
 1 1 1 0 0 0]
[1 1 0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0]


### 处理求得theta 

In [29]:
def theta(x_train, y_train):
        
    x_b = np.hstack([np.ones([len(x_train),1]),x_train]) #### x_b 为添加一列1的增广矩阵
    
    theta = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y_train)
    interception = theta[0]
    coef = theta[1:]
    return theta
        

In [30]:
def predict(x_b,theta):  
    sigmoid = 1.0/(1+np.exp(-(x_b.dot(theta))))    
    y_true = np.ones([len(sigmoid),1])
  
    for i in range(0,sigmoid.shape[0]):
        if(sigmoid[i]>=0.5):
            y_true[i] = 1
        if(sigmoid[i]<0.5):
            y_true[i] = 0
    return y_true

In [31]:
theta = theta(x_train, y_train)
theta

array([-0.21671781,  0.46832935, -0.59541426])

In [32]:
x_b = np.hstack([np.ones([len(x_test),1]),x_test]) #### x_b 为添加一列1的增广矩阵
y_sig = predict(x_b,theta)
print(y_sig)
print(y_test)
print(np.sum(y_sig == y_test)/len(y_test))

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[1 1 0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0]
8.4


In [33]:
from machine_learning.LinearRegression import LinearRegression

In [34]:
lin_reg = LinearRegression()

In [35]:
lin_reg.fit_normal(x_train, y_train)

LinearRegression()

In [37]:
lin_reg.predict(x_test)

array([ 0.85384844,  0.98964081,  0.2196033 ,  0.23231179,  0.04097902,
       -0.08681129,  0.08781196,  1.24522143,  1.07530462,  0.61968376,
        0.10922791, -0.22260366,  0.29185322,  0.04097902,  0.76889003,
        0.6109763 ,  0.67922519,  0.33868615,  0.19018529,  0.24502028])

In [38]:
lin_reg._theta

array([-0.21671781,  0.46832935, -0.59541426])

In [45]:
a = x_train[0:10,1]

In [46]:
b = y_train[:10]

In [47]:
a*(b.T)

array([0. , 0. , 3.1, 3.1, 0. , 0. , 0. , 0. , 0. , 2.9])